# R conceptos


[R new notebook](https://colab.research.google.com/notebook#create=true&language=r)

Nota: Este es un notebook hecho en colab solo por curiosidad. Recomiendo usar Rstudio si quieres aprender de forma profesional R. Aqui encontraras mis apuntes sobre el lenguaje de programacion, los conceptos basicos. 

## Install new packages

In [ ]:
install.packages("palmerpenguins")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)



## Use library

In [ ]:
library("palmerpenguins")

# Use summary for describe datasets

In [ ]:
summary(penguins)

      species          island    bill_length_mm  bill_depth_mm  
 Adelie   :152   Biscoe   :168   Min.   :32.10   Min.   :13.10  
 Chinstrap: 68   Dream    :124   1st Qu.:39.23   1st Qu.:15.60  
 Gentoo   :124   Torgersen: 52   Median :44.45   Median :17.30  
                                 Mean   :43.92   Mean   :17.15  
                                 3rd Qu.:48.50   3rd Qu.:18.70  
                                 Max.   :59.60   Max.   :21.50  
                                 NA's   :2       NA's   :2      
 flipper_length_mm  body_mass_g       sex           year     
 Min.   :172.0     Min.   :2700   female:165   Min.   :2007  
 1st Qu.:190.0     1st Qu.:3550   male  :168   1st Qu.:2007  
 Median :197.0     Median :4050   NA's  : 11   Median :2008  
 Mean   :200.9     Mean   :4202                Mean   :2008  
 3rd Qu.:213.0     3rd Qu.:4750                3rd Qu.:2009  
 Max.   :231.0     Max.   :6300                Max.   :2009  
 NA's   :2         NA's   :2                  

In [ ]:
# Head for show the first line of the data set
head(penguins, 10)

species island    bill_length_mm bill_depth_mm flipper_length_mm body_mass_g
1  Adelie  Torgersen 39.1           18.7          181               3750       
2  Adelie  Torgersen 39.5           17.4          186               3800       
3  Adelie  Torgersen 40.3           18.0          195               3250       
4  Adelie  Torgersen   NA             NA           NA                 NA       
5  Adelie  Torgersen 36.7           19.3          193               3450       
6  Adelie  Torgersen 39.3           20.6          190               3650       
7  Adelie  Torgersen 38.9           17.8          181               3625       
8  Adelie  Torgersen 39.2           19.6          195               4675       
9  Adelie  Torgersen 34.1           18.1          193               3475       
10 Adelie  Torgersen 42.0           20.2          190               4250       
   sex    year
1  male   2007
2  female 2007
3  female 2007
4  NA     2007
5  female 2007
6  male   2007
7  female 2007
8  male   2007
9  NA     2007
10 NA     2007

# Asignando valor a las variables con R

---



In [ ]:
# De esta forma R asigna valores a las variables, no usa "=" :(
n <- 2

In [ ]:
n

[1] 2

In [ ]:
# Me parece una riducules pero la flecha indica para donde va el dato. ( No se cual es la inspiracion)
5 -> n

In [ ]:
n

[1] 5

In [ ]:
# Es sencible a las mayusculas
x <- 1
X <- 10

In [ ]:
x

[1] 1

In [ ]:
X

[1] 10

## Operadores aritmeticos

In [ ]:
n <- 10 + 2 * 4 / 2 -1

In [ ]:
n

[1] 13

In [ ]:
rnorm(1) # Funciones nativas del lenguaje random normal

[1] 0.1492273

In [ ]:
2 ^ 2 # Potencia

[1] 4

In [ ]:
2 %% 2 # El modulo de toda la vida

[1] 0

In [ ]:
5 %/% 2 # Elimina decimal

[1] 2

## Funcion ls() 

In [ ]:
 name <- "Carmen"; n1 <- 10; n2 <- 100; m <- 0.5

In [ ]:
# Con esta funcion podremos ver los nombres de las variables que se encuentra en memoria
ls()

[1] "m"    "n"    "n1"   "n2"   "name" "x"    "X"

In [ ]:
ls(pat = "m") # Esto se parece mucho a las expresiones regulares

[1] "m"    "name"

In [ ]:
ls(pat = "^m")

[1] "m"

In [ ]:
 ls.str() # nos muestra ciertos detalles de nuestros datos en memoria

m :  num 0.5
n :  num 13
n1 :  num 10
n2 :  num 100
name :  chr "Carmen"
x :  num 1
X :  num 10

## Data Frames

In [ ]:
M <- data.frame(n1, n2, m)

In [ ]:
ls.str(pat="M")

M : 'data.frame':	1 obs. of  3 variables:
 $ n1: num 10
 $ n2: num 100
 $ m : num 0.5

# Solicitar ayuda

In [ ]:
?ls

In [ ]:
help("*")

In [ ]:
help("bs") # Avcs necesistas buscar en todos los paquetes para encontrar ayuda

In [ ]:
??bs # Busca en todos los paquetes

In [ ]:
help("bs", try.all.packages = TRUE)

In [ ]:
help("bs", package = "splines") # Buscar en un package en especifico

In [ ]:
help.start()

starting httpd help server ...
 done



If the browser launched by 'xdg-open' is already running, it is *not*
    restarted, and you must switch to its window.
Otherwise, be patient ...


## R tiene varios tipos de datos

In [ ]:
A <- "Gomphotherium"; compar <- TRUE; z <- 1i
mode(A); mode(compar); mode(z)

[1] "character"

[1] "logical"

[1] "complex"

In [ ]:
 N <- 2.1e23

In [ ]:
N

[1] 2.1e+23

In [ ]:
mode(N)

[1] "numeric"

In [ ]:
mode (1)

[1] "numeric"

In [ ]:
N/ 23456

[1] 8.952933e+18

## R permite la division por cero

In [ ]:
5/0 # Usa el objeto especial Inf para representar el infinito

[1] Inf

In [ ]:
mode(5/0)

[1] "numeric"

In [ ]:
Inf - Inf # Retorna un NaN

[1] NaN

#  Generating data

In [ ]:
x <- 1:30 # generando secuencia incluye el 30

In [ ]:
x

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
[26] 26 27 28 29 30

In [ ]:
1:10-1 # No ta la diferencia al usar operaciones aritmeticas

[1] 0 1 2 3 4 5 6 7 8 9

In [ ]:
1:(10-1) # 

[1] 1 2 3 4 5 6 7 8 9

In [ ]:
seq(1, 5, 0.5)

[1] 1.0 1.5 2.0 2.5 3.0 3.5 4.0 4.5 5.0

In [ ]:
seq(length=9, from=1, to=5)

[1] 1.0 1.5 2.0 2.5 3.0 3.5 4.0 4.5 5.0

In [ ]:
a <- c(1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5)

In [ ]:
mode(a)

[1] "numeric"

In [ ]:
a

[1] 1.0 1.5 2.0 2.5 3.0 3.5 4.0 4.5 5.0

In [ ]:
rep(1, 30)

[1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1

In [ ]:
sequence(4:5)

[1] 1 2 3 4 1 2 3 4 5

In [ ]:
sequence(c(10,5))

[1]  1  2  3  4  5  6  7  8  9 10  1  2  3  4  5

In [ ]:
gl(3, 5)

[1] 1 1 1 1 1 2 2 2 2 2 3 3 3 3 3
Levels: 1 2 3

In [ ]:
gl(3, 5, length=30)

[1] 1 1 1 1 1 2 2 2 2 2 3 3 3 3 3 1 1 1 1 1 2 2 2 2 2 3 3 3 3 3
Levels: 1 2 3

In [ ]:
gl(2, 6, label=c("Male", "Female"))

[1] Male   Male   Male   Male   Male   Male   Female Female Female Female
[11] Female Female
Levels: Male Female

# Creating objects

In [ ]:
factor(1:3)

[1] 1 2 3
Levels: 1 2 3

In [ ]:
factor(1:3, labels=c("A", "B", "C"))

[1] A B C
Levels: A B C

In [ ]:
matrix(data=5, nr=2, nc=2)

[,1] [,2]
[1,] 5    5   
[2,] 5    5

In [ ]:
 matrix(1:6, 2, 3, byrow=TRUE)

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

In [ ]:
x <- 1:15
x

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15

In [ ]:
dim(x)

NULL

In [ ]:
dim(x) <- c(5, 3) # Puedo covertir un arreglo en una matrix

In [ ]:
x

[,1] [,2] [,3]
[1,] 1     6   11  
[2,] 2     7   12  
[3,] 3     8   13  
[4,] 4     9   14  
[5,] 5    10   15